export const symbols = {
  chevronLeft: "chevron-left",
  chevronRight: "chevron-right",
  collection: "collection",
  infoCircle: "info-circle",
  transparency: "transparency",
  journalCheck: "journal-check",
  journalPlus: "journal-plus",
  lightningCharge: "lightning-charge",
  peopleCircle: "people-circle",
  personCheck: "person-check",
  search: "search",
  toggles2: "toggles2",
  pencilFill: "pencil-fill",
  sliders: "sliders",
  menu: "menu",
  calendar3: "calendar3",
  gearFill: "gear-fill",
  nodePlusFill: "node-plus-fill",
}
